/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminRuleRouteImport } from './routes/_authenticated/admin.rule'
import { Route as AuthenticatedAdminRiwayatRouteImport } from './routes/_authenticated/admin.riwayat'
import { Route as AuthenticatedAdminPenyakitRouteImport } from './routes/_authenticated/admin.penyakit'
import { Route as AuthenticatedAdminGejalaRouteImport } from './routes/_authenticated/admin.gejala'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRuleRoute = AuthenticatedAdminRuleRouteImport.update({
  id: '/rule',
  path: '/rule',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRiwayatRoute =
  AuthenticatedAdminRiwayatRouteImport.update({
    id: '/riwayat',
    path: '/riwayat',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPenyakitRoute =
  AuthenticatedAdminPenyakitRouteImport.update({
    id: '/penyakit',
    path: '/penyakit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGejalaRoute =
  AuthenticatedAdminGejalaRouteImport.update({
    id: '/gejala',
    path: '/gejala',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnosis': typeof DiagnosisRoute
  '/hasil': typeof HasilRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/gejala': typeof AuthenticatedAdminGejalaRoute
  '/admin/penyakit': typeof AuthenticatedAdminPenyakitRoute
  '/admin/riwayat': typeof AuthenticatedAdminRiwayatRoute
  '/admin/rule': typeof AuthenticatedAdminRuleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnosis': typeof DiagnosisRoute
  '/hasil': typeof HasilRoute
  '/tentang': typeof TentangRoute
  '/admin/gejala': typeof AuthenticatedAdminGejalaRoute
  '/admin/penyakit': typeof AuthenticatedAdminPenyakitRoute
  '/admin/riwayat': typeof AuthenticatedAdminRiwayatRoute
  '/admin/rule': typeof AuthenticatedAdminRuleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnosis': typeof DiagnosisRoute
  '/hasil': typeof HasilRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/gejala': typeof AuthenticatedAdminGejalaRoute
  '/_authenticated/admin/penyakit': typeof AuthenticatedAdminPenyakitRoute
  '/_authenticated/admin/riwayat': typeof AuthenticatedAdminRiwayatRoute
  '/_authenticated/admin/rule': typeof AuthenticatedAdminRuleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnosis'
    | '/hasil'
    | '/tentang'
    | '/admin'
    | '/admin/gejala'
    | '/admin/penyakit'
    | '/admin/riwayat'
    | '/admin/rule'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnosis'
    | '/hasil'
    | '/tentang'
    | '/admin/gejala'
    | '/admin/penyakit'
    | '/admin/riwayat'
    | '/admin/rule'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/diagnosis'
    | '/hasil'
    | '/tentang'
    | '/_authenticated/admin'
    | '/_authenticated/admin/gejala'
    | '/_authenticated/admin/penyakit'
    | '/_authenticated/admin/riwayat'
    | '/_authenticated/admin/rule'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosisRoute: typeof DiagnosisRoute
  HasilRoute: typeof HasilRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rule': {
      id: '/_authenticated/admin/rule'
      path: '/rule'
      fullPath: '/admin/rule'
      preLoaderRoute: typeof AuthenticatedAdminRuleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/riwayat': {
      id: '/_authenticated/admin/riwayat'
      path: '/riwayat'
      fullPath: '/admin/riwayat'
      preLoaderRoute: typeof AuthenticatedAdminRiwayatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/penyakit': {
      id: '/_authenticated/admin/penyakit'
      path: '/penyakit'
      fullPath: '/admin/penyakit'
      preLoaderRoute: typeof AuthenticatedAdminPenyakitRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gejala': {
      id: '/_authenticated/admin/gejala'
      path: '/gejala'
      fullPath: '/admin/gejala'
      preLoaderRoute: typeof AuthenticatedAdminGejalaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminGejalaRoute: typeof AuthenticatedAdminGejalaRoute
  AuthenticatedAdminPenyakitRoute: typeof AuthenticatedAdminPenyakitRoute
  AuthenticatedAdminRiwayatRoute: typeof AuthenticatedAdminRiwayatRoute
  AuthenticatedAdminRuleRoute: typeof AuthenticatedAdminRuleRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminGejalaRoute: AuthenticatedAdminGejalaRoute,
  AuthenticatedAdminPenyakitRoute: AuthenticatedAdminPenyakitRoute,
  AuthenticatedAdminRiwayatRoute: AuthenticatedAdminRiwayatRoute,
  AuthenticatedAdminRuleRoute: AuthenticatedAdminRuleRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosisRoute: DiagnosisRoute,
  HasilRoute: HasilRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
